[package]
name = "numl"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
description = "Implementations of various numerical algorithms with an emphasis on accuracy"
repository = "https://github.com/ItzARubix/numl"
readme = "README.md"

[dependencies]
thiserror = "2.0.15"
